micronaut:
  application:
    name: subscriptionMicroservice
  server:
    port: 8082
datasources:
  default:
    url: jdbc:mariadb://${DB_HOST:db3}/${DB_NAME:subscriptions}
    username: threedo
    password: threedosecret
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.subscription.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
