micronaut:
  application:
    name: trendingHashtagMicroservice
  server:
    port: 8081
datasources:
  default:
    url: jdbc:mariadb://${DB_HOST:db2}/${DB_NAME:hashtags}
    username: mydo
    password: mydosecret
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.trending.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
netty:
  default:
    allocator:
      max-order: 3