package uk.ac.york.eng2.subscription.domain;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.micronaut.serde.annotation.Serdeable;

/**
 * Entity declaration for the User in the subscription MS 
 * Tagged "Serialisable" so that it can be transferred via Kafka
 * 
 * <p>
 * ID is auto-generated so it can be appropriately saved in its
 * own database. Username is a simple string and the set of watched
 * videos is stored in a many to many relationship.
 * 
 * Note - ID in this case is NOT autogenerated, because it is
 * explicitly given when creating the entities in the database
 * to ensure that the entities have the same IDs of the same entity
 * in the video microservice.
 * 
 * @author Y3884331
 * @version 0.1
 * @since 0.1
 */
@Entity
@Serdeable
public class User extends BaseUser {
	
	@Id
	private Long id;
	
	@Column(nullable = false)
	private String username;
	
	@JsonIgnore
	@ManyToMany(mappedBy = "watchers")
	private Set<Video> watchedVideos;
	
	@JsonIgnore
	@ManyToMany
	private Set<Hashtag> subscribedHashtags;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	public Set<Video> getWatchedVideos() {
		return watchedVideos;
	}

	public void setWatchedVideos(Set<Video> watchedVideos) {
		this.watchedVideos = watchedVideos;
	}
	
	public Set<Hashtag> getSubscribedHashtags() {
		return subscribedHashtags;
	}
	
	public void setSubscribedHashtags(Set<Hashtag> subscribedHashtags) {
		this.subscribedHashtags = subscribedHashtags;
	}
}
