package uk.ac.york.eng2.subscription.domain;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.micronaut.serde.annotation.Serdeable;

/**
 * Entity declaration for the Hashtag in the subscription MS 
 * Tagged "Serialisable" so that it can be transferred via Kafka
 * 
 * <p>
 * ID is auto-generated so it can be appropriately saved in its
 * own database. name is a simple string and the set of tagged
 * videos is stored in a many to many relationship.
 * 
 * Note - ID in this case is NOT autogenerated, because it is
 * explicitly given when creating the entities in the database
 * to ensure that the entities have the same IDs of the same entity
 * in the video microservice.
 * 
 * @author Y3884331
 * @version 0.1
 * @since 0.1
 */
@Entity
@Serdeable
public class Hashtag extends BaseHashtag {
	
	@Id
	private Long id;
	
	@Column(nullable = false)
	private String name;
	
	@JsonIgnore
	@ManyToMany(mappedBy = "tags")
	private Set<Video> taggedVideos;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public Set<Video> getTaggedVideos() {
		return taggedVideos;
	}
	
	public void setTaggedVideos(Set<Video> taggedVideos) {
		this.taggedVideos = taggedVideos;
	}
}
