micronaut:
  application:
    name: videoMicroservice
datasources:
  default:
    url: jdbc:mariadb://${DB_HOST:db}/${DB_NAME:video}
    username: todo
    password: todosecret
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.videos.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
netty:
  default:
    allocator:
      max-order: 3