micronaut:
  application:
    name: videomicroservice
datasources:
  default:
    url: #enter database url here
    username: #enter username
    password: #enter password
    driver-class-name: #enter driver
    db-type: #enter db type
    dialect: #enter dialect
jpa:
  default:
    entity-scan:
      packages:
        - myassessment.videomicroservice.domain
      properties:
        hibernate:
          hbm2ddl:
            auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`} #alter to bootstrap server variable if necessary
netty:
  default:
    allocator:
      max-order: 3